CREATE TABLE UserLogin (
  user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL,	
  user_pass TEXT NOT NULL
)

CREATE TABLE UserCreation (
  creation_user	INTEGER REFERENCES UserLogin(user_id) ON DELETE CASCADE,
  creation_id	INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  creation_name	TEXT NOT NULL,
  creation_tea TEXT NOT NULL,
  creation_flavor	TEXT,
  creation_addons	TEXT,
  creation_milk	TEXT,
  creation_sweetener TEXT,
)

CREATE TABLE Classic (
  classic_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  classic_name TEXT NOT NULL,
  classic_tea	TEXT NOT NULL,
  classic_flavor1	TEXT,
  classic_flavor2	TEXT,
  classic_addons1	TEXT,
  classic_addons2	TEXT,
  classic_milk	TEXT,
  classic_sweetener TEXT
);
