CREATE TYPE boba_flavor AS ENUM (
  'black sesame',
  'blueberry',
  'caramel',
  'cherry',
  'chocolate',
  'coffee',
  'green apple',
  'guava',
  'hazelnut',
  'honeydew',
  'kiwi',
  'lavender',
  'lemon',
  'lychee',
  'mango',
  'matcha',
  'passion fruit',
  'peach',
  'pineapple',
  'pomegranate',
  'pumpkin spice',
  'raspberry',
  'rose',
  'strawberry',
  'taro',
  'watermelon',
  'wintermelon'
);

CREATE TYPE boba_milk AS ENUM (
  'almond milk',
  'coconut milk',
  'fresh milk',
  'oat milk',
  'soy milk'
);

CREATE TYPE boba_sweetener AS ENUM (
  'brown sugar syrup', 
  'condensed milk', 
  'honey', 
  'simple syrup'
);

CREATE TYPE boba_tea AS ENUM (
  'black tea',
  'chai tea',
  'earl grey tea',
  'green tea',
  'milk tea',
  'oolong tea',
  'thai tea'
);

CREATE TYPE boba_addons AS ENUM (
  'almond pudding',
  'aloe vera',
  'boba',
  'cheese foam',
  'crystal boba',
  'crystal jelly',
  'egg pudding',
  'grass jelly',
  'peach bits',
  'pineapple bits',
  'popping boba',
  'rainbow jelly',
  'red bean',
  'strawberry bits',
  'vanilla ice cream',
  'whipped cream'
);

CREATE TABLE BobaAddOns (
  addon_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  addon_name boba_addons NOT NULL,
  addon_recipe TEXT NOT NULL
);

CREATE TABLE BobaTea (
  tea_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tea_name boba_tea NOT NULL,
  tea_recipe TEXT NOT NULL
);

CREATE TABLE UserLogin (
  user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL,	
  user_pass TEXT NOT NULL
);

CREATE TABLE UserCreation (
  creation_user	INTEGER REFERENCES UserLogin(user_id) ON DELETE CASCADE,
  creation_id	INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  creation_name	TEXT NOT NULL,
  creation_tea INTEGER NOT NULL REFERENCES BobaTea(tea_id) ON DELETE CASCADE,
  creation_flavor1 boba_flavor DEFAULT NULL,
  creation_flavor2 boba_flavor DEFAULT NULL,
  creation_addons1 INTEGER REFERENCES BobaAddOns(addon_id) ON DELETE CASCADE DEFAULT NULL,
  creation_addons2 INTEGER REFERENCES BobaAddOns(addon_id) ON DELETE CASCADE DEFAULT NULL,
  creation_milk	boba_milk DEFAULT NULL,
  creation_sweetener boba_sweetener DEFAULT NULL
);

CREATE TABLE Classic (
  classic_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  classic_name TEXT NOT NULL,
  classic_tea INTEGER NOT NULL REFERENCES BobaTea(tea_id) ON DELETE CASCADE,
  classic_flavor1 boba_flavor,
  classic_flavor2 boba_flavor,
  classic_addons1	INTEGER REFERENCES BobaAddOns(addon_id) ON DELETE CASCADE,
  classic_addons2 INTEGER REFERENCES BobaAddOns(addon_id) ON DELETE CASCADE,
  classic_milk	boba_milk,
  classic_sweetener boba_sweetener 
);
