DROP TABLE IF EXISTS UserCreation;
DROP TABLE IF EXISTS UserLogin;
DROP TABLE IF EXISTS Classic;
DROP TABLE IF EXISTS BobaAddOns;
DROP TABLE IF EXISTS BobaTea;

DROP TYPE IF EXISTS boba_flavor;
DROP TYPE IF EXISTS boba_milk;
DROP TYPE IF EXISTS boba_sweetener;
DROP TYPE IF EXISTS boba_tea;
DROP TYPE IF EXISTS boba_addons;
