INSERT INTO UserLogin (user_name, user_pass)
VALUES
  ('dunder', '$2a$12$tu./7U6Vm15hiTfKX2eEG.Y4UeD8sgkd9tshlyoh3bFZY1EFvg2Ke');

INSERT INTO BobaTea (tea_name, tea_recipe)
VALUES 
  ('black tea', 'INSERT RECIPE HERE'),
  ('chai tea', 'INSERT RECIPE HERE'),
  ('earl grey tea', 'INSERT RECIPE HERE'),
  ('green tea', 'INSERT RECIPE HERE'),
  ('milk tea', 'INSERT RECIPE HERE'),
  ('oolong tea', 'INSERT RECIPE HERE'),
  ('thai tea', 'INSERT RECIPE HERE');
  
INSERT INTO BobaAddOns (addon_name, addon_recipe)
VALUES
  ('almond pudding', 'INSERT RECIPE HERE'),
  ('aloe vera', 'INSERT RECIPE HERE'),
  ('boba', 'INSERT RECIPE HERE'),
  ('cheese foam', 'INSERT RECIPE HERE'),
  ('crystal boba', 'INSERT RECIPE HERE'),
  ('crystal jelly', 'INSERT RECIPE HERE'),
  ('egg pudding', 'INSERT RECIPE HERE'),
  ('grass jelly', 'INSERT RECIPE HERE'),
  ('peach bits', 'INSERT RECIPE HERE'),
  ('pineapple bits', 'INSERT RECIPE HERE'),
  ('popping boba', 'INSERT RECIPE HERE'),
  ('rainbow jelly', 'INSERT RECIPE HERE'),
  ('red bean', 'INSERT RECIPE HERE'),
  ('strawberry bits', 'INSERT RECIPE HERE'),
  ('vanilla ice cream', 'INSERT RECIPE HERE'),
  ('whipped cream', 'INSERT RECIPE HERE');

INSERT INTO Classic (
  classic_name,
  classic_tea,
  classic_flavor1,	
  classic_flavor2,
  classic_addons1,	
  classic_addons2,	
  classic_milk,	
  classic_sweetener
  )
VALUES
  ('Matcha Red Bean Love', 
  5, 
  'matcha', 
  NULL, 
  13, 
  15, 
  NULL, 
  NULL),
  ('Honey Green Tea', 
  4, 
  NULL, 
  NULL, 
  3, 
  NULL, 
  'fresh milk', 
  'honey'),
  ('Wintermelon Black Tea', 
  1, 
  'wintermelon', 
  NULL, 
  3, 
  NULL, 
  NULL, 
  'simple syrup'),
  ('Peach Black Tea', 
  1, 
  'peach', 
  NULL, 
  9, 
  NULL, 
  NULL, 
  'simple syrup'),
  ('BB Fall', 
  1, 
  'caramel', 
  'pumpkin spice', 
  16, 
  NULL, 
  'oat milk', 
  'condensed milk'),
  ('Pina Colada', 
  4, 
  'pineapple', 
  NULL, 
  12, 
  NULL, 
  'coconut milk', 
  'simple syrup'),
  ('Neopalitan', 
  1, 
  'chocolate', 
  'strawberry', 
  15, 
  3, 
  'fresh milk', 
  NULL),
  ('The Taste of Chartreuse', 
  4, 
  'passion fruit', 
  'mango', 
  11, 
  NULL, 
  NULL, 
  'simple syrup'),
  ('Caramel Milk Tea', 
  5, 
  'caramel', 
  NULL, 
  3, 
  NULL, 
  NULL, 
  'brown sugar syrup'),
  ('Honey Oolong Tea', 
  6, 
  NULL, 
  NULL, 
  3, 
  NULL, 
  'fresh milk', 
  'honey'),
  ('Berry Strawberry', 
  1, 
  'strawberry', 
  NULL, 
  14, 
  NULL, 
  NULL, 
  'brown sugar syrup'),
  ('Melona Mania', 
  4, 
  'honeydew', 
  'watermelon', 
  5, 
  NULL, 
  NULL, 
  'condensed milk'),
  ('The Cheese', 
  4, 
  NULL, 
  NULL, 
  4, 
  3, 
  NULL, 
  'simple syrup'),
  ('Honey Lavender Earl Grey', 
  3, 
  'lavender', 
  NULL, 
  NULL, 
  NULL, 
  'soy milk', 
  'honey'),
  ('3 Bean Soup', 
  1, 
  'coffee', 
  NULL, 
  13, 
  NULL, 
  'soy milk', 
  'condensed milk');

INSERT INTO UserCreation (
  creation_user,	
  creation_name,	
  creation_tea, 
  creation_flavor1,
  creation_flavor2, 
  creation_addons1, 
  creation_addons2, 
  creation_milk,
  creation_sweetener
  )
VALUES
  (1, 'THIS IS A TEST 1', 1, null, null, null, null, null, null);