INSERT INTO Classic (
  classic_name,
  classic_tea,
  classic_flavor1,	
  classic_flavor2,
  classic_addons1,	
  classic_addons2,	
  classic_milk,	
  classic_sweetener
  )
VALUES
  ('Matcha Red Bean Love', 
  'milk tea', 
  'matcha', 
  '', 
  'red bean', 
  'vanilla ice cream', 
  '', 
  ''),
  ('Honey Green Tea', 
  'green tea', 
  '', 
  '', 
  'egg pudding', 
  '', 
  'fresh milk', 
  'honey'),
  ('Wintermelon Black Tea', 
  'black tea', 
  'wintermelon', 
  '', 
  'boba', 
  '', 
  '', 
  'simple syrup'),
  ('Peach Black Tea', 
  'black tea', 
  'peach', 
  '', 
  '', 
  '', 
  '', 
  'simple syrup'),
  ('BB Fall', 
  'black tea', 
  'caramel', 
  'pumpkin spice', 
  'whipped cream', 
  '', 
  'oat milk', 
  'condensed milk'),
  ('Pina Colada', 
  'green tea', 
  'coconut', 
  'pineapple', 
  'rainbow jelly', 
  '', 
  '', 
  'simple syrup'),
  ('Neopalitan', 
  'black tea', 
  'chocolate', 
  'strawberry', 
  'vanilla ice cream', 
  'boba', 
  'fresh milk', 
  ''),
  ('The Taste of chartreuse', 
  'green tea', 
  'passion fruit', 
  'mango', 
  'popping boba', 
  '', 
  '', 
  'simple syrup'),
  ('Caramel Milk Tea', 
  'milk tea', 
  'caramel', 
  '', 
  'boba', 
  '', 
  '', 
  'brown sugar syrup'),
  ('Honey Oolong Tea', 
  'oolong tea', 
  'boba', 
  '', 
  '', 
  '', 
  'fresh milk', 
  'honey'),
  ('Berry Strawberry', 
  'black tea', 
  'strawberry', 
  'strawberry bits', 
  '', 
  '', 
  '', 
  'brown sugar syrup'),
  ('Melona Mania', 
  'green tea', 
  'honeydew', 
  'watermelon', 
  'crystal boba', 
  '', 
  '', 
  'condensed milk'),
  ('The Cheese', 
  'green tea', 
  '', 
  '', 
  'cheese foam', 
  'boba', 
  '', 
  'simple syrup'),
  ('Honey Lavender Earl Grey', 
  'earl grey', 
  'lavender', 
  '', 
  '', 
  '', 
  'soy milk', 
  'honey'),
  ('3 Bean Soup', 
  'black tea', 
  'coffee', 
  '', 
  'red bean', 
  '', 
  'soy milk', 
  'condensed milk');
